[project]
name = "InterviewTBD"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.2",
    "anthropic>=0.75.0",
    "asyncpg>=0.31.0",
    "boto3>=1.42.16",
    "fastapi>=0.124.4",
    "fastapi-clerk-auth>=0.0.9",
    "httpx[http2]>=0.28.1",
    "pydantic-settings>=2.12.0",
    "python-multipart>=0.0.21",
    "sqlmodel>=0.0.27",
    "svix>=1.83.0",
    "tenacity>=9.1.2",
    "uvicorn>=0.38.0",
]


[dependency-groups]
dev = [
    "ruff>=0.14.10",
]


[tool.ruff]
line-length = 120


[tool.ruff.format]
quote-style = "single"


[tool.ruff.lint]
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
]


[tool.ruff.lint.isort]
known-third-party = ["alembic"]


[tool.alembic]
script_location = "%(here)s/alembic"
file_template = "%%(year)d-%%(month).2d-%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s"
truncate_slug_length = 40
prepend_sys_path = [
    "."
]

# Timezone to use when rendering the date within the migration file as well as the filename.
# If specified, requires the tzdata library which can be installed by adding `alembic[tz]` to dependencies.
# String value is passed to ZoneInfo(); leave blank for localtime
# timezone =

[[tool.alembic.post_write_hooks]]
name = "ruff-lint"
type = "exec"
executable = "ruff"
options = "check --fix REVISION_SCRIPT_FILENAME"

[[tool.alembic.post_write_hooks]]
name = "ruff-format"
type = "exec"
executable = "ruff"
options = "format REVISION_SCRIPT_FILENAME"
