from anthropic import APIConnectionError, APIStatusError, AsyncAnthropic
from pydantic import BaseModel, Field, ValidationError

from app.core.config import settings


class ClaudeServiceError(Exception):
    """Raised when there is an error interacting with the Claude API."""


QUESTION_GENERATION_PROMPT = """\
You are an expert interview coach. Based on the following job description, generate \
exactly 5 behavioral interview questions that are tailored to this specific role.

Company: {company_name}
Job Title: {job_title}

Job Description:
{job_description_text}

Generate 5 behavioral interview questions that:
1. Are specific to this role and company
2. Follow the STAR method (Situation, Task, Action, Result)
3. Test relevant competencies for this position
4. Are clear and professionally worded
5. Cover different aspects of the role
"""


RESPONSE_EVALUATION_PROMPT = """\
You are an expert interview coach evaluating a candidate's response to a behavioral interview question.

Company: {company_name}

Job Title: {job_title}

Job Description:
{job_description_text}

Interview Question:
{question_text}

Candidate's Response:
{transcript}

Evaluate the response on the following criteria (score 1-10 for each):

1. **Confidence**: How confident and self-assured does the candidate sound?
2. **Clarity/Structure**: How well-structured and clear is the response? Does it follow STAR method?
3. **Technical Depth**: How well does the response demonstrate relevant technical/domain knowledge?
4. **Communication Skills**: How effectively does the candidate communicate their ideas?
5. **Relevance/Alignment**: How well does the response align with the job requirements?

For each category, provide:
- A score from 1 to 10
- Concise, actionable feedback (2-3 sentences)

Also provide an overall comment summarizing the response quality and key areas for improvement.
"""


class QuestionsList(BaseModel):
    """Response schema for interview questions generated by Claude."""

    questions: list[str] = Field(
        min_length=5,
        max_length=5,
        description='List of exactly 5 behavioral interview questions',
    )


class Scores(BaseModel):
    """Schema for scores of each evaluation category."""

    confidence: int = Field(ge=1, le=10, description='Confidence score 1-10')
    clarity_structure: int = Field(ge=1, le=10, description='Clarity/Structure score 1-10')
    technical_depth: int = Field(ge=1, le=10, description='Technical depth score 1-10')
    communication_skills: int = Field(ge=1, le=10, description='Communication skills score 1-10')
    relevance: int = Field(ge=1, le=10, description='Relevance score 1-10')


class Feedback(BaseModel):
    """Schema for detailed feedback of each evaluation category."""

    confidence: str = Field(description='Feedback on confidence')
    clarity_structure: str = Field(description='Feedback on clarity/structure')
    technical_depth: str = Field(description='Feedback on technical depth')
    communication_skills: str = Field(description='Feedback on communication skills')
    relevance: str = Field(description='Feedback on relevance')


class Evaluation(BaseModel):
    """Response schema for interview response evaluation by Claude."""

    scores: Scores
    feedback: Feedback
    overall_comment: str = Field(description='Overall assessment and improvement areas')


class ClaudeService:
    """
    Service to interact with the Claude API.

    Handles all Claude API communication for generating behavioral interview
    questions using structured outputs. Configured with API key and model
    from application settings.
    """

    def __init__(self):
        """Initialize the ClaudeService with async API client and model settings."""
        self.client = AsyncAnthropic(api_key=settings.CLAUDE_API_KEY)
        self.model = settings.CLAUDE_MODEL

    async def generate_question(self, job_description_text: str, company_name: str, job_title: str) -> list[str]:
        """
        Generate 5 behavioral interview questions using Claude API.

        Uses Claude's structured output feature to generate STAR method-based
        questions tailored to the specific role and company.
        Returns a list of exactly 5 questions.

        Raises:
            ClaudeServiceError: If API call fails or returns invalid output
        """
        try:
            response = await self.client.beta.messages.parse(
                model=self.model,
                max_tokens=2000,
                betas=['structured-outputs-2025-11-13'],
                messages=[
                    {
                        'role': 'user',
                        'content': QUESTION_GENERATION_PROMPT.format(
                            company_name=company_name,
                            job_title=job_title,
                            job_description_text=job_description_text,
                        ),
                    }
                ],
                output_format=QuestionsList,
            )
        except APIConnectionError as e:
            raise ClaudeServiceError(f'Failed to connect to Claude API: {str(e)}') from e
        except APIStatusError as e:
            raise ClaudeServiceError(f'Claude API request failed: {str(e)}. Status code: {e.status_code}') from e
        except ValidationError as e:
            raise ClaudeServiceError(f'Failed to validate Claude API response: {str(e)}') from e
        except Exception as e:
            raise ClaudeServiceError(
                f'Unexpected error during question generation. {type(e).__name__}: {str(e)}'
            ) from e

        questions_list = response.parsed_output

        if questions_list is None:
            raise ClaudeServiceError(
                'Claude API returned empty response. The model may have failed to generate structured output.'
            )

        return questions_list.questions

    async def evaluate_response(
        self, job_description_text: str, company_name: str, job_title: str, question_text: str, transcript: str
    ) -> Evaluation:
        """
        Evaluate candidate's response to an interview question using Claude API.

        Uses Claude's structured output feature to evaluate the response on
        multiple criteria and provide scores and feedback. Returns an Evaluation object
        containing scores, feedback, and overall comment, which can be serialized to JSON
        for database storage.

        Raises:
            ClaudeServiceError: If API call fails or returns invalid output
        """
        try:
            response = await self.client.beta.messages.parse(
                model=self.model,
                max_tokens=3000,
                betas=['structured-outputs-2025-11-13'],
                messages=[
                    {
                        'role': 'user',
                        'content': RESPONSE_EVALUATION_PROMPT.format(
                            company_name=company_name,
                            job_title=job_title,
                            job_description_text=job_description_text,
                            question_text=question_text,
                            transcript=transcript,
                        ),
                    }
                ],
                output_format=Evaluation,
            )
        except APIConnectionError as e:
            raise ClaudeServiceError(f'Failed to connect to Claude API: {str(e)}') from e
        except APIStatusError as e:
            raise ClaudeServiceError(f'Claude API request failed: {str(e)}. Status code: {e.status_code}') from e
        except ValidationError as e:
            raise ClaudeServiceError(f'Failed to validate Claude API response: {str(e)}') from e
        except Exception as e:
            raise ClaudeServiceError(
                f'Unexpected error during response evaluation. {type(e).__name__}: {str(e)}'
            ) from e

        evaluation = response.parsed_output

        if evaluation is None:
            raise ClaudeServiceError(
                'Claude API returned empty response. The model may have failed to generate structured output.'
            )

        return evaluation


claude_service = ClaudeService()
