from openai import APIConnectionError, APIStatusError, AsyncOpenAI
from pydantic import BaseModel, Field, ValidationError
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    stop_after_delay,
    stop_any,
    wait_exponential_jitter,
)

from app.core.config import settings


class OpenAIServiceError(Exception):
    """Raised when there is an error interacting with the OpenAI API."""


QUESTION_GENERATION_INSTRUCTIONS = """\
You are an expert interview coach generating realistic behavioural interview questions.

Generate exactly 5 behavioral interview questions that:
1. Are specific to this role and company
2. Follow the STAR method (Situation, Task, Action, Result)
3. Test relevant competencies for this position
4. Are clear and professionally worded
5. Cover different aspects of the role \
(e.g., leadership, problem-solving, teamwork, technical skills, conflict resolution)
"""


QUESTION_GENERATION_PROMPT = """\
Company: {company_name}
Job Title: {job_title}

Job Description:
{job_description_text}

Generate exactly 5 behavioral interview questions tailored to this specific role.
Each question should target a different competency relevant to the position.
"""


RESPONSE_EVALUATION_INSTRUCTIONS = """\
You are an expert interviewer evaluating a candidate's response to a behavioral interview question.

Evaluate the response objectively on the following criteria using a 1-5 scale:

**Scoring Rubric:**

1: Poor - Fails to meet expectations
2: Below Average - Significant weaknesses
3: Average - Meets basic expectations
4: Good - Exceeds expectations in most areas
5: Excellent - Outstanding, exemplary response

**Evaluation Criteria:**

1. **Confidence**: How confident and self-assured does the candidate sound?
   - Consider tone, certainty, and conviction in their answers

2. **Clarity/Structure**: How well-structured is the response? 
   - Does it follow STAR method (Situation, Task, Action, Result)?
   - Is the narrative clear and easy to follow?

3. **Technical Depth**: How well does the response demonstrate relevant knowledge?
   - Consider domain expertise, technical accuracy, and depth of understanding

4. **Communication Skills**: How effectively does the candidate communicate?
   - Consider conciseness and professionalism

5. **Relevance/Alignment**: How well does the response align with job requirements?
   - Consider role-specific competencies and company fit

For each criterion:
- Assign a score (1-5)
- Provide 2-3 sentences of specific, actionable feedback
- Reference concrete examples from the response

For the whole response, also provide an overall assessment (3-5 sentences) that:
- Summarizes strengths and weaknesses
- Provides 2-3 specific, actionable recommendations for improvement

Be fair, objective, and consistent. Focus on observable behaviors in the transcript.
"""


RESPONSE_EVALUATION_PROMPT = """\
Company: {company_name}

Job Title: {job_title}

Job Description:
{job_description_text}

Interview Question:
{question_text}

Candidate's Response:
{transcript}

Provide a detailed evaluation.
"""


class QuestionsList(BaseModel):
    """Response schema for interview questions generated by OpenAI."""

    questions: list[str] = Field(
        min_length=5,
        max_length=5,
        description='List of exactly 5 behavioral interview questions',
    )


class CriterionEvaluation(BaseModel):
    """Schema for evaluation of a single criterion."""

    score: int = Field(ge=1, le=5, description='Score from 1-5')
    feedback: str = Field(description='2-3 sentences of specific, actionable feedback with concrete examples')


class InterviewEvaluation(BaseModel):
    """Schema for structured evaluation of a candidate's interview response."""

    confidence: CriterionEvaluation
    clarity_structure: CriterionEvaluation
    technical_depth: CriterionEvaluation
    communication_skills: CriterionEvaluation
    relevance_alignment: CriterionEvaluation

    overall_assessment: str = Field(
        description='3-5 sentence summary of strengths and weaknesses with actionable recommendations'
    )


class OpenAIService:
    """
    Service to interact with the OpenAI API.

    Handles all OpenAI API communication for generating behavioral interview
    questions using structured outputs. Configured with API key and model
    from application settings.
    """

    def __init__(self):
        """Initialize the OpenAIService instance."""
        self._client: AsyncOpenAI | None = None
        self._model = settings.AZURE_OPENAI_MODEL

    def start(self):
        """Start the service by initializing the OpenAI API client."""
        self._client = AsyncOpenAI(
            base_url=settings.AZURE_OPENAI_BASE_URL,
            api_key=settings.AZURE_OPENAI_API_KEY,
        )

    async def stop(self):
        """Close the service's OpenAI API client."""
        if self._client is not None:
            await self._client.close()

    def _ensure_started(self) -> AsyncOpenAI:
        """
        Ensure the service has been started and return the non-None client.

        Raises:
            OpenAIServiceError: If the service has not been started
        """
        if self._client is None:
            raise OpenAIServiceError('OpenAIService has not been started. Call start() before using the service.')
        return self._client

    @retry(
        stop=stop_any(stop_after_attempt(3), stop_after_delay(30)),
        wait=wait_exponential_jitter(initial=1, max=10, jitter=1),
        retry=retry_if_exception_type(OpenAIServiceError),
        reraise=True,
    )
    async def generate_question(self, job_description_text: str, company_name: str, job_title: str) -> list[str]:
        """
        Generate 5 behavioral interview questions using OpenAI API.

        Uses OpenAI's structured output feature to generate STAR method-based
        questions tailored to the specific role and company.
        Returns a list of exactly 5 questions.

        Raises:
            OpenAIServiceError: If API call fails or returns invalid output
        """
        client = self._ensure_started()
        try:
            response = await client.responses.parse(
                model=self._model,
                max_output_tokens=2000,
                temperature=0.7,
                instructions=QUESTION_GENERATION_INSTRUCTIONS,
                input=QUESTION_GENERATION_PROMPT.format(
                    company_name=company_name,
                    job_title=job_title,
                    job_description_text=job_description_text,
                ),
                text_format=QuestionsList,
            )
        except APIConnectionError as e:
            raise OpenAIServiceError(f'Failed to connect to OpenAI API: {str(e)}') from e
        except APIStatusError as e:
            raise OpenAIServiceError(f'OpenAI API request failed: {str(e)}. Status code: {e.status_code}') from e
        except ValidationError as e:
            raise OpenAIServiceError(f'Failed to validate OpenAI API response: {str(e)}') from e
        except Exception as e:
            raise OpenAIServiceError(
                f'Unexpected error during question generation. {type(e).__name__}: {str(e)}'
            ) from e

        questions_list = response.output_parsed

        if questions_list is None:
            raise OpenAIServiceError(
                'OpenAI API returned empty response. The model may have failed to generate structured output.'
            )

        return questions_list.questions

    @retry(
        stop=stop_any(stop_after_attempt(3), stop_after_delay(30)),
        wait=wait_exponential_jitter(initial=1, max=10, jitter=1),
        retry=retry_if_exception_type(OpenAIServiceError),
        reraise=True,
    )
    async def evaluate_response(
        self, job_description_text: str, company_name: str, job_title: str, question_text: str, transcript: str
    ) -> InterviewEvaluation:
        """
        Evaluate candidate's response to an interview question using OpenAI API.

        Uses OpenAI's structured output feature to evaluate the response on
        multiple criteria and provide scores and feedback. Returns an Evaluation object
        containing scores, feedback, and overall comment, which can be serialized to JSON
        for database storage.

        Raises:
            OpenAIServiceError: If API call fails or returns invalid output
        """
        client = self._ensure_started()
        try:
            response = await client.responses.parse(
                model=self._model,
                max_output_tokens=3000,
                temperature=0.1,
                instructions=RESPONSE_EVALUATION_INSTRUCTIONS,
                input=RESPONSE_EVALUATION_PROMPT.format(
                    company_name=company_name,
                    job_title=job_title,
                    job_description_text=job_description_text,
                    question_text=question_text,
                    transcript=transcript,
                ),
                text_format=InterviewEvaluation,
            )
        except APIConnectionError as e:
            raise OpenAIServiceError(f'Failed to connect to OpenAI API: {str(e)}') from e
        except APIStatusError as e:
            raise OpenAIServiceError(f'OpenAI API request failed: {str(e)}. Status code: {e.status_code}') from e
        except ValidationError as e:
            raise OpenAIServiceError(f'Failed to validate OpenAI API response: {str(e)}') from e
        except Exception as e:
            raise OpenAIServiceError(
                f'Unexpected error during response evaluation. {type(e).__name__}: {str(e)}'
            ) from e

        evaluation = response.output_parsed

        if evaluation is None:
            raise OpenAIServiceError(
                'OpenAI API returned empty response. The model may have failed to generate structured output.'
            )

        return evaluation


openai_service = OpenAIService()
